version: '2'

services:
  mongo:
    restart: always
    image: mongo:3.4
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

  postgres:
    restart: always
    image: postgres:9.5-alpine
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - variables.env

  mysql:
    build: ./docker/mysql
    restart: always
    image: mysql:5.7
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
      - ./conf/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
        - variables.env

  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    ports:
      - "8080:80"
    env_file:
      - variables.env

  memcached:
    restart: always
    image: memcached:1.4-alpine
    ports:
      - "11211:11211"

  queue:
    restart: always
    image: phalconphp/beanstalkd:1.10
    ports:
      - "11300:11300"
    volumes:
      - beanstalk:/var/lib/beanstalkd

  aerospike:
    restart: always
    image: aerospike:latest
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    volumes:
      - aerospike:/opt/aerospike/data

  redis:
    restart: always
    image: redis:3.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  elasticsearch:
    image: elasticsearch:5.2-alpine
    restart: always
    expose:
      - "9200"
      - "9300"
    ports:
      - "9200:9200"
      - "9300:9300"
    env_file:
      - variables.env
    volumes:
      - esdata:/usr/share/elasticsearch/data
  
  node_app:
    image: node:9.4
    build: ./docker/node_app
    restart: always
    working_dir: /project/application/ManagerPlatform
    expose:
      - "8000"
    ports:
      - "8000:8000"
    # volumes_from:
      # - app
    volumes:
      - .:/project
      - /project/application/ManagerPlatform/node_modules
    depends_on:
      - app

  app:
    build: ./docker/app
    restart: always
    working_dir: /project
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/project
      - /project/application/vendor
      - ./conf/php/cli.ini:/etc/php/7.0/cli/conf.d/99-custom.ini
      - ./conf/php/fpm.ini:/etc/php/7.0/fpm/conf.d/99-custom.ini
    depends_on:
      - mysql
      - queue
      - redis
      - memcached
      - elasticsearch
    env_file:
      - variables.env
  
volumes:
  mongo:
    driver: local
  postgres:
    driver: local
  mysql:
    driver: local
  beanstalk:
    driver: local
  redis:
    driver: local
  aerospike:
    driver: local
  esdata:
    driver: local
